apiKey: "" # ключ API Ozon из этого раздела: https://seller.ozon.ru/app/settings/api-keys
companyID: 123 # идентификатор компании из этого же раздела
cookie: "" # значение кукисов Озона из браузера
groups:
  -
    id: product-article # Идентификатор группы товаров, в рамках которой будет ротация акций
    articles: [product-article-1, product-article-2, product-article-3] # Артикулы продавца товаров, учавствующих в акции
    in-promotions: 2 # Максимальное количество в акции
    minimal-promotion: true # Добавлять ли в акцию по максимально возможной скидке. Иначе, если false или по-умолчанию, добавляются товары с максимальным продвижением по минимальной цене
